# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "weasel-the-memory-watcher"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Curtis Schofield", "www.goodreads.com"]
  s.date = "2013-01-15"
  s.description = "Dedicated to my dead cat and goodreads.com"
  s.email = "github.com@robotarmyma.de"
  s.executables = ["weasel"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/weasel",
    "lib/memory_watch.rb",
    "lib/weasel.rb",
    "test/helper.rb",
    "test/test_memory_watch.rb"
  ]
  s.homepage = "http://github.com/robotarmy/weasel"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Weasel : The memory wacher"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
  end
end

